# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - RoastMeai

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_5374c5374b35478b9c925bca0e8a78a1 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_83f8f252cd074fc6a7f4e19155cb17fe }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_5374c5374b35478b9c925bca0e8a78a1 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'RoastMeai'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_dd5ea364bb034bebb8e699d2c9f7ce95 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_5374c5374b35478b9c925bca0e8a78a1 }}/appsvc/staticsite:${{ github.sha }}'